[world]
name = "ByteBeasts Tamagotchi"
description = "This is the first game in the on-chain ByteBeasts universe."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/ByteBuildersLabs/BabyBeastsv2"
seed = "tamagotchi23"

[world.socials]
x = "https://x.com/0xByteBeasts"
github = "https://github.com/ByteBuildersLabs/BabyBeastsv2"
telegram = "https://t.me/+-84e2pqLtqNkZDAx"

[namespace]
default = "tamagotchi"

[env]
rpc_url = "https://api.cartridge.gg/x/starknet/sepolia/0.8.1"

[writers]
"tamagotchi" = ["tamagotchi-game", "tamagotchi-player", "tamagotchi-achieve"]
"tamagotchi-TrophyCreation" = ["tamagotchi-achieve"]
"tamagotchi-TrophyProgression" = ["tamagotchi-achieve"]
