[world]
name = "ByteBeasts Tamagotchi"
description = "This is the first game in the on-chain ByteBeasts universe."
cover_uri = "file://assets/cover.png"
icon_uri = "file://assets/icon.png"
website = "https://github.com/ByteBuildersLabs/BabyBeastsv2"
seed = "tamagotchi"

[world.socials]
x = "https://x.com/0xByteBeasts"
github = "https://github.com/ByteBuildersLabs/BabyBeastsv2"
telegram = "https://t.me/+-84e2pqLtqNkZDAx"

[namespace]
default = "tamagotchi"

[env]
rpc_url = "https://api.cartridge.gg/x/bytebeaststamagotchi/katana"
account_address = "0x5b6b8189bb580f0df1e6d6bec509ff0d6c9be7365d10627e0cf222ec1b47a71"
private_key = "0x33003003001800009900180300d206308b0070db00121318d17b5e6262150b"
# world_address = "0x06171ed98331e849d6084bf2b3e3186a7ddf35574dd68cab4691053ee8ab69d7"

[writers]
"tamagotchi" = ["tamagotchi-game", "tamagotchi-player"]
"tamagotchi-TrophyCreation" = ["tamagotchi-player"]
"tamagotchi-TrophyProgression" = ["tamagotchi-player"]
